FROM mariadb:latest

ENV MYSQL_ROOT_PASSWORD=Velizy78@
ENV MYSQL_DATABASE=defaultdb
ENV MYSQL_USER=lucas.dinnichert.pro@gmail.com
ENV MYSQL_PASSWORD=Velizy78@

RUN apt-get update && apt-get install -y openssh-client

RUN echo "[mysqld]" >> /etc/mysql/my.cnf &&     echo "bind-address = 0.0.0.0" >> /etc/mysql/my.cnf

# Copier la clé SSH
COPY ./id_rsa /root/.ssh/id_rsa
COPY ./id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 600 /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa.pub &&     ssh-keyscan github.com >> /root/.ssh/known_hosts

