FROM nginx:latest

RUN apt-get update && apt-get install -y nano git openssh-client mailutils npm

COPY ./id_rsa /root/.ssh/id_rsa
COPY ./id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 600 /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa.pub &&     ssh-keyscan github.com >> /root/.ssh/known_hosts

